steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gcp-sbcl-woo/sbcl-woo', '-f', 'Dockerfile', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gcp-sbcl-woo/sbcl-woo']

images: ['gcr.io/gcp-sbcl-woo/sbcl-woo']
